---
version: "3"
services:
  flask-docker:
    build: .
    container_name: flask-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${HOST_PORT}:5000
    restart: unless-stopped
